### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by blacksmithop** [Dan6erbond/aPRAW#46]
**Describe the bug**
> A clear and concise description of what the bug is.

Possible missing `await`
```python
C:\Users\kvgk2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\apraw\reddit.py:190: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(wait_time)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
**To Reproduce**
> The code with which the issue can be reproduced.

```python
import apraw
import asyncio

# instantiate a `Reddit` instance
# you can also supply a key to an entry within a praw.ini
# file, making your login compatible with praw as well
reddit = apraw.Reddit(....)


async def scan_posts():
    # get an instance of a subreddit
    subreddit = await reddit.subreddit("aprawtest")

    # loop through new posts
    async for submission in subreddit.new():
        print(submission.title)


if __name__ == "__main__":
    # get the asyncio event loop
    loop = asyncio.get_event_loop()

    # add scan_posts() to the queue and run it
    loop.run_until_complete(scan_posts())

```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Noticed a Runtimewarning

**Environment**
> A clear and concise description of what your environment looks like.

 - **OS:**  Windows
 - **Python version:**  3.6
 - **aPRAW version:** [e.g. 0.2.0-alpha]

**Additional context**
> Add any other context about the problem here.

**Comment by Dan6erbond** [comment]
Hi @blacksmithop, thank you for your bug report. This bug has been identified and fixed in #44. The changes will be included in the next major aPRAW release.

EDIT: Additionally, you should remove the sensitive user information included in your reproducible code and change the combination for your safety.
