### ISSUE TITLE
[ENDPOINT] Search Endpoint Issue Subbreddit.Search

### ISSUE THREAD

**Issue by pranavanp** [Dan6erbond/aPRAW#47]
**Endpoint name:** `` [e.g. `subreddit_wiki`]

**Endpoint path:** `` [e.g. `/r/subreddit/api/wiki`]

**Expected model/function:** `` [e.g. `apraw.models.Submission.mod.delete()`]

**Additional context**
> Add any other context about the endpoint here.

**Comment by Dan6erbond** [comment]
This issue does not follow the issue template's guidelines and will be closed. Please make a new one and fill out all the fields.
